### ISSUE TITLE
Race class

### ISSUE THREAD

**Issue by Valenrieu** [lucaskoensgen/pcs_scraper#4]
I tried to use the Race class, but most of the methods I tried didn't work. For instance, I tried the get_startlist method, and got an AttributeError : Nonetype has no attribute find.

**Comment by lucaskoensgen** [comment]
looks like pcs updated some of their web forms...i'll touch up the code to access the new table formats

**Comment by lucaskoensgen** [comment]
fyi before updating anything, the stage results pages still work – you could obtain the startlist by going through the names of the riders in the first stage results.
ex: get_stage_result('stage-1')
